baseURL = 'https://intaktfinland.fi/'
theme = "ananke"

defaultContentLanguage = 'fi'
[languages]
  [languages.fi]
    title = 'Ehjä ry'
    weight = 1
  [languages.en]
    title = 'Intact Finland'
    weight = 3
  [languages.sv]
    title = 'Intakt rf'
    weight = 2
